### ISSUE TITLE
Eclipse Issues

### ISSUE THREAD

**Issue by MayankHirani** [jmwolff3/java_teaching#1]
When using eclipse, I was unable to import Scanner, and a few errors came up. After uninstalling and reinstalling, these errors still occurred, including the 'Polling News Error'. 
In addition, the source folder of my files did not show up after reinstalling.
Should I try another IDE in the meantime?

**Comment by jmwolff3** [comment]
Are you able to import java.util? Make sure you have a 64bit JDK installed. https://www.oracle.com/technetwork/java/javase/downloads/index.html

Disable news feed polling. To do so, go to Preferences... -> General -> News, and untick the Enable automatic news polling option.

**Comment by MayankHirani** [comment]
It is working fine now. Thanks.
